import type { Flashcard } from "./types";

// Corporate finance: DCF, WACC, P/E, enterprise value vs equity value.
// IDs are permanent (progress is keyed on them) - add new cards with new ids.

export const CORPORATE_FINANCE: Flashcard[] = [
  {
    id: "cf-01",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "What is a DCF valuation?",
    back: "It values a business as the present value of its expected future free cash flows, discounted at a rate that reflects their risk (usually WACC for unlevered free cash flow), plus the present value of a terminal value.",
  },
  {
    id: "cf-02",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "How do you calculate unlevered free cash flow?",
    back: "EBIT × (1 − tax rate)\n+ depreciation & amortisation\n− capital expenditure\n− increase in net working capital\n\nIt's the cash available to all providers of capital, before interest.",
  },
  {
    id: "cf-03",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "What is the present value formula? Give an example.",
    back: "PV = cash flow ÷ (1 + r)^t\n\n£110 received in one year, discounted at 10%: 110 ÷ 1.10 = £100.",
  },
  {
    id: "cf-04",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "Why do we discount future cash flows?",
    back: "Time value of money: a pound today can be invested to earn a return. And risk: future cash flows are uncertain. The discount rate is the return investors require for that risk.",
  },
  {
    id: "cf-05",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "What are the two main ways to calculate terminal value?",
    back: "1. Perpetuity growth (Gordon growth): TV = FCF in year n × (1 + g) ÷ (WACC − g).\n2. Exit multiple: a final-year metric (e.g. EBITDA) × a multiple taken from comparable companies.",
  },
  {
    id: "cf-06",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "In the perpetuity growth method, why must g be below WACC? What is a sensible g?",
    back: "If g ≥ WACC the formula breaks down (it implies infinite or negative value). A business can't outgrow the economy forever, so long-run g is usually set around long-run nominal GDP growth or inflation - often 2-3%.",
  },
  {
    id: "cf-07",
    deckId: "corporate-finance",
    topic: "DCF",
    front: "What happens to a DCF valuation if WACC rises?",
    back: "Value falls: future cash flows are discounted more heavily. The terminal value, which is often most of a DCF, is especially sensitive.",
  },
  {
    id: "cf-08",
    deckId: "corporate-finance",
    topic: "WACC",
    front: "What is WACC and its formula?",
    back: "Weighted average cost of capital: the blended return required by all capital providers.\n\nWACC = E/(D+E) × cost of equity + D/(D+E) × cost of debt × (1 − tax rate)\n\nUse market values of debt (D) and equity (E).",
  },
  {
    id: "cf-09",
    deckId: "corporate-finance",
    topic: "WACC",
    front: "Why is the cost of debt multiplied by (1 − tax rate) in WACC?",
    back: "Interest is tax-deductible, so each £1 of interest reduces the tax bill. The after-tax cost of debt is lower than the headline rate (the 'tax shield').",
  },
  {
    id: "cf-10",
    deckId: "corporate-finance",
    topic: "WACC",
    front: "What is CAPM?",
    back: "Capital Asset Pricing Model - estimates the cost of equity:\n\nCost of equity = risk-free rate + β × (expected market return − risk-free rate)\n\nThe risk-free rate is often a government bond yield (e.g. the 10-year gilt); the bracket is the equity risk premium.",
  },
  {
    id: "cf-11",
    deckId: "corporate-finance",
    topic: "WACC",
    front: "What does beta measure?",
    back: "Systematic (market) risk: how much a share tends to move relative to the market. β = 1 moves with the market; β > 1 is more volatile; β < 1 is less volatile.",
  },
  {
    id: "cf-12",
    deckId: "corporate-finance",
    topic: "WACC",
    front: "Why is equity usually more expensive than debt?",
    back: "Shareholders are paid last (a residual claim) and have no guaranteed return, so they bear more risk and demand a higher return. Debt also gets a tax shield because interest is deductible.",
  },
  {
    id: "cf-13",
    deckId: "corporate-finance",
    topic: "EV vs equity value",
    front: "What is the difference between enterprise value and equity value?",
    back: "Enterprise value (EV): the value of the core operating business to all capital providers (debt and equity).\nEquity value: the value belonging to shareholders only - for a listed company, its market capitalisation.",
  },
  {
    id: "cf-14",
    deckId: "corporate-finance",
    topic: "EV vs equity value",
    front: "How do you get from equity value to enterprise value?",
    back: "EV = equity value + debt + preferred shares + non-controlling interests − cash and cash equivalents.\n\nSimplified: EV = market cap + net debt.",
  },
  {
    id: "cf-15",
    deckId: "corporate-finance",
    topic: "EV vs equity value",
    front: "Why is cash subtracted when calculating enterprise value?",
    back: "Cash isn't part of the operating business. A buyer of the whole company effectively gets the cash back, so it reduces the net cost of acquiring the operations.",
  },
  {
    id: "cf-16",
    deckId: "corporate-finance",
    topic: "EV vs equity value",
    front: "A company issues £100m of new shares for cash. What happens to equity value and EV?",
    back: "Equity value rises by £100m. Cash rises by £100m, so net debt falls by £100m. EV is unchanged: financing decisions don't change the value of the operating business (ignoring what the cash is later spent on).",
  },
  {
    id: "cf-17",
    deckId: "corporate-finance",
    topic: "Multiples",
    front: "Which multiples use EV and which use equity value?",
    back: "Match the numerator to the capital providers behind the denominator.\n\nEV multiples use pre-interest metrics: EV/Revenue, EV/EBITDA, EV/EBIT.\nEquity multiples use post-interest metrics: P/E (net income), price-to-book.",
  },
  {
    id: "cf-18",
    deckId: "corporate-finance",
    topic: "Multiples",
    front: "What is the P/E ratio?",
    back: "Share price ÷ earnings per share (equivalently, market cap ÷ net income).\n\nIt shows how much investors pay for each £1 of annual earnings.",
  },
  {
    id: "cf-19",
    deckId: "corporate-finance",
    topic: "Multiples",
    front: "What might a high P/E tell you?",
    back: "Investors expect strong future growth, see the company as lower risk - or the shares are overvalued. Compare with peers and with growth; the PEG ratio (P/E ÷ EPS growth rate) adjusts for growth.",
  },
  {
    id: "cf-20",
    deckId: "corporate-finance",
    topic: "Multiples",
    front: "Why doesn't P/E work for a loss-making company? What could you use instead?",
    back: "With negative earnings, P/E is meaningless. Use EV/Revenue, EV/EBITDA if EBITDA is positive, or a DCF.",
  },
];
